id: P003046
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS19204
  title: གསོ་དཔྱད་རྒྱལ་པོའི་དཀོར་མཛོད་དང་ཕན་བདེ་འབུམ་ཕྲག་དང་ཡང་སྙིང་།
  author: ''
  volumes:
    36203ac2d2a24da184fb0d135d595d1f:
      image_group_id: I8LS19206
      title: ''
      volume_number: 1
      total_pages: 508
      base_file: v001.txt
